export const placards = [
    {
      "Id": 1,
      "First_Name": "Maria",
      "Last_Name": "Ramos",
      "Address": "6177 Fishburn Ave",
      "Phone_Number": "323 360 4037",
      "Email": "ramos.rrj@gmail.com",
      "Vehicle_One_License_Plate": "4CJR607",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Explorer",
      "Vehicle_One_Year": 1998,
      "Assigned_Parking_Stall_Number": 1
    },
    {
      "Id": 2,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 2
    },
    {
      "Id": 3,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 3
    },
    {
      "Id": 4,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 4
    },
    {
      "Id": 5,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 5
    },
    {
      "Id": 6,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 6
    },
    {
      "Id": 7,
      "First_Name": "Frances",
      "Last_Name": "Saucedo",
      "Address": "6176 Otis AVe",
      "Phone_Number": "323 635 8139",
      "Email": "frances.saucedo@ymail.com",
      "Vehicle_One_License_Plate": "8LYF360",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Charger",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 7
    },
    {
      "Id": 8,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 8
    },
    {
      "Id": 9,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 9
    },
    {
      "Id": 10,
      "First_Name": "Ronald",
      "Last_Name": "Chacon",
      "Address": "4119 Randolph ST",
      "Phone_Number": "323 338 4863",
      "Email": "none",
      "Vehicle_One_License_Plate": "6DLW781",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 10
    },
    {
      "Id": 11,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 11
    },
    {
      "Id": 12,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 12
    },
    {
      "Id": 13,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 13
    },
    {
      "Id": 14,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 14
    },
    {
      "Id": 15,
      "First_Name": "Benigno",
      "Last_Name": "Madriles",
      "Address": "4069 Randolph St",
      "Phone_Number": "323 495 7569",
      "Email": "none",
      "Vehicle_One_License_Plate": "7ZIT951",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Escape",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 15
    },
    {
      "Id": 16,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 16
    },
    {
      "Id": 17,
      "First_Name": "Luis",
      "Last_Name": "Esparza",
      "Address": "4059 Randolph St",
      "Phone_Number": "323 771 7451",
      "Email": "esparzaluis1201@yahoo.com",
      "Vehicle_One_License_Plate": "8NRE626",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 17
    },
    {
      "Id": 18,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 18
    },
    {
      "Id": 19,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 19
    },
    {
      "Id": 20,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 20
    },
    {
      "Id": 21,
      "First_Name": "Adalberto",
      "Last_Name": "Sanchez",
      "Address": "4021 Randolph St",
      "Phone_Number": "323 715 8436",
      "Email": "none",
      "Vehicle_One_License_Plate": "6ZLF869",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "CRV",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 21
    },
    {
      "Id": 22,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 22
    },
    {
      "Id": 23,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 23
    },
    {
      "Id": 24,
      "First_Name": "Jorge",
      "Last_Name": "Vasquez",
      "Address": "4011 Randolph St",
      "Phone_Number": "323 251 4972",
      "Email": "none",
      "Vehicle_One_License_Plate": "YUNIVA",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Rav4",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 24
    },
    {
      "Id": 25,
      "First_Name": "Marina",
      "Last_Name": "Grajeda",
      "Address": "6176 Corona Ave",
      "Phone_Number": "323 354 5756",
      "Email": "conniegrajeda1964@gmail.com",
      "Vehicle_One_License_Plate": "6T17937",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2000,
      "Assigned_Parking_Stall_Number": 25
    },
    {
      "Id": 26,
      "First_Name": "Irma",
      "Last_Name": "Barragan",
      "Address": "3927 Randolph St",
      "Phone_Number": "323 712 7029",
      "Email": "Irbarragan@yahoo.com",
      "Vehicle_One_License_Plate": "56413J2",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Silverado",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 26
    },
    {
      "Id": 27,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 27
    },
    {
      "Id": 28,
      "First_Name": "Teresa",
      "Last_Name": "McNally",
      "Address": "3921 Randolph St",
      "Phone_Number": "323 771 6355",
      "Email": "N/A",
      "Vehicle_One_License_Plate": "7XDC299",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 28
    },
    {
      "Id": 29,
      "First_Name": "Ruben",
      "Last_Name": "Flores",
      "Address": "3917 Randolph St",
      "Phone_Number": "323 901 9969",
      "Email": "ricardog6952@gmail.com",
      "Vehicle_One_License_Plate": "356y367",
      "Vehicle_One_Make": "VW",
      "Vehicle_One_Model": "Jetta",
      "Vehicle_One_Year": 1996,
      "Assigned_Parking_Stall_Number": 29
    },
    {
      "Id": 30,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 30
    },
    {
      "Id": 31,
      "First_Name": "Juan",
      "Last_Name": "Rodriguez",
      "Address": "3913 Randolph ST",
      "Phone_Number": "323 350 3524",
      "Email": "zuzychavez@me.com",
      "Vehicle_One_License_Plate": "D265H0",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Soul",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 31
    },
    {
      "Id": 32,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 32
    },
    {
      "Id": 33,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 33
    },
    {
      "Id": 34,
      "First_Name": "Lourdes",
      "Last_Name": "Gonzalez",
      "Address": "3821 Randolph St",
      "Phone_Number": "323 485 1846",
      "Email": "lulug1710@hotmail.com",
      "Vehicle_One_License_Plate": "7MHF523",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic EX",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 34
    },
    {
      "Id": 35,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 35
    },
    {
      "Id": 36,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 36
    },
    {
      "Id": 37,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 37
    },
    {
      "Id": 38,
      "First_Name": "Miguel",
      "Last_Name": "Cruz",
      "Address": "3807 Randolph St",
      "Phone_Number": "323 560 2778",
      "Email": "none",
      "Vehicle_One_License_Plate": "8TEN128",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Accord",
      "Vehicle_One_Year": 2020,
      "Assigned_Parking_Stall_Number": 38
    },
    {
      "Id": 39,
      "First_Name": "Jose Ricardo",
      "Last_Name": "Cardenas",
      "Address": "3803 Randolph St #A",
      "Phone_Number": "323 773 6515",
      "Email": "cardenas2203@gmail.com",
      "Vehicle_One_License_Plate": "8DSA879",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 39
    },
    {
      "Id": 40,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 40
    },
    {
      "Id": 41,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 41
    },
    {
      "Id": 42,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 42
    },
    {
      "Id": 43,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 43
    },
    {
      "Id": 44,
      "First_Name": "Triny",
      "Last_Name": "Ochoa",
      "Address": "3747 Randolph St",
      "Phone_Number": "323 492 8959",
      "Email": "triny8a@hotmail.com",
      "Vehicle_One_License_Plate": "7XXA717",
      "Vehicle_One_Make": "Volkswagon",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 44
    },
    {
      "Id": 45,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 45
    },
    {
      "Id": 46,
      "First_Name": "Veronica",
      "Last_Name": "Vaca",
      "Address": "3741 Randolph St",
      "Phone_Number": "323 560 1613",
      "Email": "verogiron75@yahoo.com",
      "Vehicle_One_License_Plate": "8L02978",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Tundra",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 46
    },
    {
      "Id": 47,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 47
    },
    {
      "Id": 48,
      "First_Name": "Elodia",
      "Last_Name": "Rivas",
      "Address": "3737 Randolph St",
      "Phone_Number": "213 281 0813",
      "Email": "brisa_rivas@yahoo.com",
      "Vehicle_One_License_Plate": "8B7B734",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Optima",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 48
    },
    {
      "Id": 49,
      "First_Name": "Donna",
      "Last_Name": "Carroll",
      "Address": "3725 Randolph ST",
      "Phone_Number": "323 667 4005",
      "Email": "e9281@lapd.online",
      "Vehicle_One_License_Plate": "8PIB679",
      "Vehicle_One_Make": "KIA",
      "Vehicle_One_Model": "Fort",
      "Vehicle_One_Year": 2020,
      "Assigned_Parking_Stall_Number": 49
    },
    {
      "Id": 50,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 50
    },
    {
      "Id": 51,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 51
    },
    {
      "Id": 52,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 52
    },
    {
      "Id": 53,
      "First_Name": "Martin",
      "Last_Name": "Perez",
      "Address": "3717 Randolph St",
      "Phone_Number": "323 582 8504",
      "Email": "marperrob03@gmail.com",
      "Vehicle_One_License_Plate": "6JVK692",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "NA",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 53
    },
    {
      "Id": 54,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 54
    },
    {
      "Id": 55,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 55
    },
    {
      "Id": 56,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 56
    },
    {
      "Id": 57,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 57
    },
    {
      "Id": 58,
      "First_Name": "Marcos",
      "Last_Name": "Martinez",
      "Address": "3647 Randolph St",
      "Phone_Number": "323 274 5105",
      "Email": "none",
      "Vehicle_One_License_Plate": "8JQD129",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Fit",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 58
    },
    {
      "Id": 59,
      "First_Name": "Ana",
      "Last_Name": "Flores",
      "Address": "3643 Randolph St",
      "Phone_Number": "323 570 7631",
      "Email": "ana.flores1354@gmail.com",
      "Vehicle_One_License_Plate": "7WLF786",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 1997,
      "Assigned_Parking_Stall_Number": 59
    },
    {
      "Id": 60,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 60
    },
    {
      "Id": 61,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 61
    },
    {
      "Id": 62,
      "First_Name": "Juana",
      "Last_Name": "Monroy",
      "Address": "3631 Randolph ST",
      "Phone_Number": "323 581 1540",
      "Email": "jennyblue16@yahoo.com",
      "Vehicle_One_License_Plate": "6HDN120",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Sienna",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 62
    },
    {
      "Id": 63,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 63
    },
    {
      "Id": 64,
      "First_Name": "Agustin",
      "Last_Name": "Guerrero",
      "Address": "3625 Randolph St",
      "Phone_Number": "323 605 3239",
      "Email": "auguerr78@outlook.com",
      "Vehicle_One_License_Plate": "7MW2076",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Traverse",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 64
    },
    {
      "Id": 65,
      "First_Name": "Jacobo",
      "Last_Name": "Lujan",
      "Address": "3621 Randolph St",
      "Phone_Number": "323 677 8762",
      "Email": "jacobo3621@gmail.com",
      "Vehicle_One_License_Plate": "5SHX421",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 65
    },
    {
      "Id": 66,
      "First_Name": "Ana",
      "Last_Name": "Garcia",
      "Address": "3611 Randolph St",
      "Phone_Number": "323 327 3882",
      "Email": "mail_4_ana@gmail.com",
      "Vehicle_One_License_Plate": "6LCG321",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "CRV",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 66
    },
    {
      "Id": 67,
      "First_Name": "Jose",
      "Last_Name": "Cruz",
      "Address": "3607 Randolph ST",
      "Phone_Number": "323 456 6777",
      "Email": "none",
      "Vehicle_One_License_Plate": "8APP741",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2012,
      "Assigned_Parking_Stall_Number": 67
    },
    {
      "Id": 68,
      "First_Name": "Alfredo",
      "Last_Name": "Cruz",
      "Address": "3603 Randolph",
      "Phone_Number": "323 440 3396",
      "Email": "none",
      "Vehicle_One_License_Plate": "26743J1",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Ram",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 68
    },
    {
      "Id": 69,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 69
    },
    {
      "Id": 70,
      "First_Name": "Parking",
      "Last_Name": "Not Claimed",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 70
    },
    {
      "Id": 71,
      "First_Name": "Patricia",
      "Last_Name": "Ortiz",
      "Address": "3529 Randolph St",
      "Phone_Number": "323 819 8945",
      "Email": "portiz741@gmail.com",
      "Vehicle_One_License_Plate": "4GWG220",
      "Vehicle_One_Make": "Checy",
      "Vehicle_One_Model": "SV",
      "Vehicle_One_Year": 1997,
      "Assigned_Parking_Stall_Number": 71
    },
    {
      "Id": 72,
      "First_Name": "Orlando A.",
      "Last_Name": "Valencia Bran",
      "Address": "3525 Randolph ST",
      "Phone_Number": "213 248 5203",
      "Email": "alexvbran@yahoo.com",
      "Vehicle_One_License_Plate": "8HSW522",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "RAV4",
      "Vehicle_One_Year": 2013,
      "Assigned_Parking_Stall_Number": 72
    },
    {
      "Id": 73,
      "First_Name": "Maria",
      "Last_Name": "Holguin",
      "Address": "3521 Randolph ST",
      "Phone_Number": "323 363 5462",
      "Email": "caramelo.holguin@gmail.com",
      "Vehicle_One_License_Plate": "5EGS483",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Accord",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 73
    },
    {
      "Id": 74,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 74
    },
    {
      "Id": 75,
      "First_Name": "Daily",
      "Last_Name": "Parking",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 75
    },
    {
      "Id": 101,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 101
    },
    {
      "Id": 102,
      "First_Name": "Maria",
      "Last_Name": "Ramos",
      "Address": "3177 Fishburn Ave",
      "Phone_Number": "323 360 4037",
      "Email": "none",
      "Vehicle_One_License_Plate": "4RPH008",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "na",
      "Vehicle_One_Year": 2001,
      "Assigned_Parking_Stall_Number": 102
    },
    {
      "Id": 103,
      "First_Name": "Estanislao",
      "Last_Name": "Gutierrez",
      "Address": "6111 Fishburn",
      "Phone_Number": "323 707 0658",
      "Email": "tane.69@att.net",
      "Vehicle_One_License_Plate": "8J34754",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Silverado",
      "Vehicle_One_Year": 1997,
      "Assigned_Parking_Stall_Number": 103
    },
    {
      "Id": 104,
      "First_Name": "Abelardo",
      "Last_Name": "Cruz",
      "Address": "6055 Fishburn Ave Apt B",
      "Phone_Number": "323 613 4872",
      "Email": "antoniamunguia47@yahoo.com",
      "Vehicle_One_License_Plate": "8JXV795",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Explorer",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 104
    },
    {
      "Id": 105,
      "First_Name": "Arnold",
      "Last_Name": "Vega",
      "Address": "6123 Otis Ave #B",
      "Phone_Number": "323 972 7694",
      "Email": "vegaarnold26@gmail.com",
      "Vehicle_One_License_Plate": "8DMX750",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 105
    },
    {
      "Id": 106,
      "First_Name": "Hazel",
      "Last_Name": "Aranda",
      "Address": "4215 Randolph St",
      "Phone_Number": "626 548 0982",
      "Email": "haselaranda@gmail.com",
      "Vehicle_One_License_Plate": "6EPJ380",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Accord",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 106
    },
    {
      "Id": 107,
      "First_Name": "Servando",
      "Last_Name": "Molina",
      "Address": "6130 Otis Ave Apt F",
      "Phone_Number": "323 495 2436",
      "Email": "molina2822@gmail.com",
      "Vehicle_One_License_Plate": "7RVP650",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 107
    },
    {
      "Id": 108,
      "First_Name": "Maria",
      "Last_Name": "Vasquez",
      "Address": "6164 Otis Ave",
      "Phone_Number": "323 587 9808",
      "Email": "none",
      "Vehicle_One_License_Plate": "5UGW755",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 108
    },
    {
      "Id": 109,
      "First_Name": "Salvador",
      "Last_Name": "Flores",
      "Address": "6130 Otis Ave Apt F",
      "Phone_Number": "323 598 2825",
      "Email": "big2dieck@gmail.com",
      "Vehicle_One_License_Plate": "7GZN461",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 109
    },
    {
      "Id": 110,
      "First_Name": "San Juan",
      "Last_Name": "Quintil",
      "Address": "4215 Randolph St",
      "Phone_Number": "323 493 4355",
      "Email": "quintil27@yahoo.com",
      "Vehicle_One_License_Plate": "8PLR282",
      "Vehicle_One_Make": "Audi",
      "Vehicle_One_Model": "NA",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 110
    },
    {
      "Id": 111,
      "First_Name": "Wilfredo",
      "Last_Name": "Rodriguez",
      "Address": "6164 Otis Ave",
      "Phone_Number": "323 674 4152",
      "Email": "none",
      "Vehicle_One_License_Plate": "7GFP130",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2014,
      "Assigned_Parking_Stall_Number": 111
    },
    {
      "Id": 112,
      "First_Name": "Wilfredo",
      "Last_Name": "Rodriguez",
      "Address": "6164 Otis Ave",
      "Phone_Number": "323 674 4152",
      "Email": "bertrodriguez197500@gmail.com",
      "Vehicle_One_License_Plate": "4FIN275",
      "Vehicle_One_Make": "Jeep",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 1999,
      "Assigned_Parking_Stall_Number": 112
    },
    {
      "Id": 113,
      "First_Name": "Jose",
      "Last_Name": "Castellanos",
      "Address": "6169 Otis",
      "Phone_Number": "323 204 6576",
      "Email": "josecocado32@gmail.com",
      "Vehicle_One_License_Plate": "8UKC289",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Explorer",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 113
    },
    {
      "Id": 114,
      "First_Name": "Cynthia",
      "Last_Name": "Rodriguez",
      "Address": "6160 Otis Ave",
      "Phone_Number": "323 955 9546",
      "Email": "cynthiarodrigues839@gmail.com",
      "Vehicle_One_License_Plate": "8KDP080",
      "Vehicle_One_Make": "Toyora",
      "Vehicle_One_Model": "Yaris",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 114
    },
    {
      "Id": 115,
      "First_Name": "Frances",
      "Last_Name": "Saucedo",
      "Address": "6176 Otis Ave",
      "Phone_Number": "323 635 8139",
      "Email": "frances.saucedo@ymail.com",
      "Vehicle_One_License_Plate": "4URA279",
      "Vehicle_One_Make": "Cadillac",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2002,
      "Assigned_Parking_Stall_Number": 115
    },
    {
      "Id": 121,
      "First_Name": "Ronald",
      "Last_Name": "Chacon",
      "Address": "4119 Randolph St",
      "Phone_Number": "323 338 4863",
      "Email": "none",
      "Vehicle_One_License_Plate": "3XXD844",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Passport",
      "Vehicle_One_Year": 1998,
      "Assigned_Parking_Stall_Number": 121
    },
    {
      "Id": 122,
      "First_Name": "Jerry",
      "Last_Name": "Chacon",
      "Address": "4119 Randolph ST",
      "Phone_Number": "323 855 9944",
      "Email": "jchacon@ups.com",
      "Vehicle_One_License_Plate": "TICOR8R",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Silverado",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 122
    },
    {
      "Id": 123,
      "First_Name": "Paola Morero",
      "Last_Name": "Preciado",
      "Address": "6021 Otis Ave Apt E",
      "Phone_Number": "323 396 6884",
      "Email": "lovepaula44@gmail.com",
      "Vehicle_One_License_Plate": "4ZSA004",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": "2003",
      "Assigned_Parking_Stall_Number": 123
    },
    {
      "Id": 124,
      "First_Name": "Alondra",
      "Last_Name": "Andrade",
      "Address": "6150 Riverside Ave",
      "Phone_Number": "626 6759519",
      "Email": "aguilaradriana@icloud.com",
      "Vehicle_One_License_Plate": "6ZYF793",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "CRV",
      "Vehicle_One_Year": 2013,
      "Assigned_Parking_Stall_Number": 124
    },
    {
      "Id": 125,
      "First_Name": "Salvador",
      "Last_Name": "Urbina",
      "Address": "6117 Riverside Ave #B",
      "Phone_Number": "323 530 4758",
      "Email": "salvaurbina65@gmaill.com",
      "Vehicle_One_License_Plate": "5CUV374",
      "Vehicle_One_Make": "Potiac",
      "Vehicle_One_Model": "Sunfire",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 125
    },
    {
      "Id": 126,
      "First_Name": "Michael",
      "Last_Name": "Nava",
      "Address": "4113 Randolph St Unit #2",
      "Phone_Number": "323 406 3449",
      "Email": "michael_nava@aol.com",
      "Vehicle_One_License_Plate": "6VYP293",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Durango",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 126
    },
    {
      "Id": 131,
      "First_Name": "Irma Tania",
      "Last_Name": "Garcia Barahona",
      "Address": "6155 Gifford Ave",
      "Phone_Number": "323 773 2557",
      "Email": "none",
      "Vehicle_One_License_Plate": "5XBU619",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 131
    },
    {
      "Id": 132,
      "First_Name": "Kathy",
      "Last_Name": "Flores",
      "Address": "6122 Gifford Ave Apt B",
      "Phone_Number": "323 482 8838",
      "Email": "kathy3578@sbcglobal.net",
      "Vehicle_One_License_Plate": "7MPX996",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 132
    },
    {
      "Id": 133,
      "First_Name": "Rosa",
      "Last_Name": "Betancourt",
      "Address": "6053 Loma Vista",
      "Phone_Number": "323 210 9652",
      "Email": "none",
      "Vehicle_One_License_Plate": "7XJF830",
      "Vehicle_One_Make": "GMC",
      "Vehicle_One_Model": "Terrain",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 133
    },
    {
      "Id": 134,
      "First_Name": "Victor",
      "Last_Name": "Garcia",
      "Address": "6156 Gifford Ave Apt C",
      "Phone_Number": "323 892 9226",
      "Email": "garciabatz1985@gmail.com",
      "Vehicle_One_License_Plate": "8LAK808",
      "Vehicle_One_Make": "Hyundai",
      "Vehicle_One_Model": "Accent",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 134
    },
    {
      "Id": 135,
      "First_Name": "Victor",
      "Last_Name": "Garcia",
      "Address": "6156 Gifford Ave Apt C",
      "Phone_Number": "323 892 9226",
      "Email": "garciabatz1985@gmail.com",
      "Vehicle_One_License_Plate": "8ALR299",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 135
    },
    {
      "Id": 136,
      "First_Name": "Elizeth",
      "Last_Name": "Figueroa",
      "Address": "6156 Gifford Ave Apt A",
      "Phone_Number": "323 972 7953",
      "Email": "cheeks213@yahoo.com",
      "Vehicle_One_License_Plate": "97150R2",
      "Vehicle_One_Make": "GMC",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 136
    },
    {
      "Id": 137,
      "First_Name": "Benigno",
      "Last_Name": "Madriles",
      "Address": "4069 Randolph St",
      "Phone_Number": "323 495 7569",
      "Email": "none",
      "Vehicle_One_License_Plate": "7J0z619",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Altima",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 137
    },
    {
      "Id": 138,
      "First_Name": "Cecilia",
      "Last_Name": "Cortez",
      "Address": "4055 Randolph st",
      "Phone_Number": "323 557 6887",
      "Email": "none",
      "Vehicle_One_License_Plate": "8AJX720",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 138
    },
    {
      "Id": 139,
      "First_Name": "Alma",
      "Last_Name": "Moran",
      "Address": "6156 Riverside Ave",
      "Phone_Number": "323 807 9712",
      "Email": "almas1223@gmail.com",
      "Vehicle_One_License_Plate": "LBREMER",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Odyssey",
      "Vehicle_One_Year": 2002,
      "Assigned_Parking_Stall_Number": 139
    },
    {
      "Id": 140,
      "First_Name": "Elizabeth",
      "Last_Name": "Vital",
      "Address": "6157 Riverside Ave #1",
      "Phone_Number": "323 603 1100",
      "Email": "lizzie07914@yahoo.com",
      "Vehicle_One_License_Plate": "7PYL419",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2002,
      "Assigned_Parking_Stall_Number": 140
    },
    {
      "Id": 141,
      "First_Name": "Hipoloto",
      "Last_Name": "Martinez",
      "Address": "4053 Randolph ST",
      "Phone_Number": "213 926 8548",
      "Email": "none",
      "Vehicle_One_License_Plate": "7UXN419",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Freestar",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 141
    },
    {
      "Id": 142,
      "First_Name": "Teodoro",
      "Last_Name": "Contreras",
      "Address": "6159 Riverside Ave",
      "Phone_Number": "323 309 9741",
      "Email": "none",
      "Vehicle_One_License_Plate": "5FNM330",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Bronco",
      "Vehicle_One_Year": 1988,
      "Assigned_Parking_Stall_Number": 142
    },
    {
      "Id": 143,
      "First_Name": "Teodoro",
      "Last_Name": "Contreras",
      "Address": "6159 Riverside St",
      "Phone_Number": "323 309 9741",
      "Email": "contrerasteodoro1@gmail.com",
      "Vehicle_One_License_Plate": "6CGE677",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Expedition",
      "Vehicle_One_Year": 1999,
      "Assigned_Parking_Stall_Number": 143
    },
    {
      "Id": 151,
      "First_Name": "Roberto Carlos",
      "Last_Name": "De la Cruz",
      "Address": "6150 Riverside Ave",
      "Phone_Number": "626 253 3787",
      "Email": "aguilaradriana@icloud.com",
      "Vehicle_One_License_Plate": "20550A1",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "NONE",
      "Vehicle_One_Year": 2010,
      "Assigned_Parking_Stall_Number": 151
    },
    {
      "Id": 152,
      "First_Name": "Maria isabel",
      "Last_Name": "Lares",
      "Address": "6157 Riverside Ave # C",
      "Phone_Number": "323 773 6150",
      "Email": "none",
      "Vehicle_One_License_Plate": "7RAK383",
      "Vehicle_One_Make": "Acura",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 152
    },
    {
      "Id": 153,
      "First_Name": "Kevin",
      "Last_Name": "Garcia",
      "Address": "6069 Riverside Ave",
      "Phone_Number": "323 359 6048",
      "Email": "garciakun@gmail.com",
      "Vehicle_One_License_Plate": "7VPN242",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 153
    },
    {
      "Id": 154,
      "First_Name": "Maria",
      "Last_Name": "Estrada",
      "Address": "6159 Riverside Ave #A",
      "Phone_Number": "323 204 7372",
      "Email": "mscrisestrada@yahoo.com",
      "Vehicle_One_License_Plate": "7Y31271",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2002,
      "Assigned_Parking_Stall_Number": 154
    },
    {
      "Id": 155,
      "First_Name": "Leticia",
      "Last_Name": "Flores",
      "Address": "6159 Riverside",
      "Phone_Number": "323 773 8418",
      "Email": "none",
      "Vehicle_One_License_Plate": "4YJB805",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Explorer",
      "Vehicle_One_Year": 1992,
      "Assigned_Parking_Stall_Number": 155
    },
    {
      "Id": 156,
      "First_Name": "Leticia",
      "Last_Name": "Flores",
      "Address": "6159 Riverside",
      "Phone_Number": "323 773 8418",
      "Email": "none",
      "Vehicle_One_License_Plate": "5DCC068",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Altima",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 156
    },
    {
      "Id": 157,
      "First_Name": "Jorge",
      "Last_Name": "Vasquez",
      "Address": "4011 Randolph St",
      "Phone_Number": "323 251 4972",
      "Email": "none",
      "Vehicle_One_License_Plate": "8RXT901",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "HR-V",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 157
    },
    {
      "Id": 158,
      "First_Name": "Jorge",
      "Last_Name": "Vasquez",
      "Address": "4011 Randolph St",
      "Phone_Number": "323 251 4972",
      "Email": "none",
      "Vehicle_One_License_Plate": "8D92034",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Titan",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 158
    },
    {
      "Id": 159,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 159
    },
    {
      "Id": 160,
      "First_Name": "Mariela Rodriguez",
      "Last_Name": "Hernandez",
      "Address": "4023 Randolph St",
      "Phone_Number": "323 399 6551",
      "Email": "marielarodriguez123@gmail.com",
      "Vehicle_One_License_Plate": "5GJJ794",
      "Vehicle_One_Make": "Jeep",
      "Vehicle_One_Model": "Liberty",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 160
    },
    {
      "Id": 161,
      "First_Name": "Mario",
      "Last_Name": "Perez",
      "Address": "4015 Randolph St",
      "Phone_Number": "310 493 9420",
      "Email": "perezperlita@gmail.com",
      "Vehicle_One_License_Plate": "8EAJ586",
      "Vehicle_One_Make": "Chevrolet",
      "Vehicle_One_Model": "Malibu",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 161
    },
    {
      "Id": 162,
      "First_Name": "Jonathan",
      "Last_Name": "Rodriguez",
      "Address": "6150 Corona Ave",
      "Phone_Number": 3235408764,
      "Email": "rodj5490@chsphantoms.org",
      "Vehicle_One_License_Plate": "7SXW727",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 162
    },
    {
      "Id": 163,
      "First_Name": "Julio",
      "Last_Name": "Guzman",
      "Address": "6116 Corona Ave",
      "Phone_Number": "323 218 6885",
      "Email": "none",
      "Vehicle_One_License_Plate": "5UYP520",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 163
    },
    {
      "Id": 171,
      "First_Name": "Ismael",
      "Last_Name": "Munoz",
      "Address": "6151 Corona Ave",
      "Phone_Number": "213 494 3905",
      "Email": "none",
      "Vehicle_One_License_Plate": "special case",
      "Vehicle_One_Make": "special",
      "Vehicle_One_Model": "case",
      "Vehicle_One_Year": 0,
      "Assigned_Parking_Stall_Number": 171
    },
    {
      "Id": 172,
      "First_Name": "Ismael",
      "Last_Name": "Munoz",
      "Address": "6151 Corona Ave",
      "Phone_Number": "213 494 3905",
      "Email": "none",
      "Vehicle_One_License_Plate": "special case",
      "Vehicle_One_Make": "special",
      "Vehicle_One_Model": "case",
      "Vehicle_One_Year": 0,
      "Assigned_Parking_Stall_Number": 172
    },
    {
      "Id": 173,
      "First_Name": "Vivian",
      "Last_Name": "Plascencia",
      "Address": "6170 Corona Ave",
      "Phone_Number": "323 919 5205",
      "Email": "none",
      "Vehicle_One_License_Plate": "7SQL385",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "LIT",
      "Vehicle_One_Year": 2006,
      "Assigned_Parking_Stall_Number": 173
    },
    {
      "Id": 174,
      "First_Name": "Rafael",
      "Last_Name": "Gonzalez",
      "Address": "6160 Corona Ave",
      "Phone_Number": "323 854 4589",
      "Email": "none",
      "Vehicle_One_License_Plate": "7F12450",
      "Vehicle_One_Make": "GMC",
      "Vehicle_One_Model": "Sienna",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 174
    },
    {
      "Id": 175,
      "First_Name": "Marina",
      "Last_Name": "Grajeda",
      "Address": "6176 Corona Ave",
      "Phone_Number": "323 354 5756",
      "Email": "conniegrajeda1964@gmail.com",
      "Vehicle_One_License_Plate": "7MRU248",
      "Vehicle_One_Make": "Volks",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2001,
      "Assigned_Parking_Stall_Number": 175
    },
    {
      "Id": 176,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 176
    },
    {
      "Id": 177,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 177
    },
    {
      "Id": 178,
      "First_Name": "Zuzy",
      "Last_Name": "Chavez de Rodriguz",
      "Address": "3913 Randolph St",
      "Phone_Number": "323 350 3524",
      "Email": "zuzychavez@me.com",
      "Vehicle_One_License_Plate": "7JYZ590",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Soul",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 178
    },
    {
      "Id": 179,
      "First_Name": "Zuzy",
      "Last_Name": "Chavez de Rodriguez",
      "Address": "3913 Randolph St",
      "Phone_Number": "323 350 3524",
      "Email": "zuzychavez@me.com",
      "Vehicle_One_License_Plate": "7KXL332",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Soul",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 179
    },
    {
      "Id": 180,
      "First_Name": "Christian",
      "Last_Name": "Navarro",
      "Address": "6131 1/2 Bear Ave",
      "Phone_Number": "661 578 3653",
      "Email": "reeene@hotmail.com",
      "Vehicle_One_License_Plate": "8RNC106",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Altima",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 180
    },
    {
      "Id": 181,
      "First_Name": "Adriana",
      "Last_Name": "Aviles",
      "Address": "3815 Randolph st",
      "Phone_Number": "323 407 1017",
      "Email": "adreeexoxo@gmail.com",
      "Vehicle_One_License_Plate": "7JJN804",
      "Vehicle_One_Make": "Volkwagen",
      "Vehicle_One_Model": "Jetta",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 181
    },
    {
      "Id": 182,
      "First_Name": "Edgar",
      "Last_Name": "Munoz Puentes",
      "Address": "6163 Carmelita Ave Apt. B",
      "Phone_Number": "562 441 0399",
      "Email": "edgarmunozd96@gmail.com",
      "Vehicle_One_License_Plate": "7DZD889",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Prius Plug-in",
      "Vehicle_One_Year": 2014,
      "Assigned_Parking_Stall_Number": 182
    },
    {
      "Id": 183,
      "First_Name": "Elida",
      "Last_Name": "Cabrera",
      "Address": "3815 Randolph",
      "Phone_Number": "562 688 8744",
      "Email": "none",
      "Vehicle_One_License_Plate": "6LPM730",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "NA",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 183
    },
    {
      "Id": 191,
      "First_Name": "Jennifer",
      "Last_Name": "Gutierrez",
      "Address": "3821 Randolph St",
      "Phone_Number": "323 314 1566",
      "Email": "jenngee28@gmail.com",
      "Vehicle_One_License_Plate": "7HMV634",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Optima",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 191
    },
    {
      "Id": 192,
      "First_Name": "Ana",
      "Last_Name": "Gonzalez",
      "Address": "3821 Randolph ST",
      "Phone_Number": "323 314 8156",
      "Email": "anagon722@yahoo.com",
      "Vehicle_One_License_Plate": "8EPF890",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 192
    },
    {
      "Id": 193,
      "First_Name": "Elio",
      "Last_Name": "Gonzalez",
      "Address": "3821 Randolph St",
      "Phone_Number": "323 289 5164",
      "Email": "none",
      "Vehicle_One_License_Plate": "7NMG676",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 193
    },
    {
      "Id": 194,
      "First_Name": "Sugey",
      "Last_Name": "Diaz",
      "Address": "3821 Randolph St",
      "Phone_Number": "323 404 3468",
      "Email": "none",
      "Vehicle_One_License_Plate": "8CYR988",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": 86,
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 194
    },
    {
      "Id": 195,
      "First_Name": "Jose",
      "Last_Name": "Munguia",
      "Address": "6122 Corona Ave",
      "Phone_Number": "323 592 4973",
      "Email": "josemunguia3@gmail.com",
      "Vehicle_One_License_Plate": "8MLK165",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2013,
      "Assigned_Parking_Stall_Number": 195
    },
    {
      "Id": 196,
      "First_Name": "Veronica",
      "Last_Name": "Vaca",
      "Address": "3741 Randolph St",
      "Phone_Number": "323 560 1613",
      "Email": "verogiron75@yahoo.com",
      "Vehicle_One_License_Plate": "7KYE459",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 196
    },
    {
      "Id": 197,
      "First_Name": "Rolando",
      "Last_Name": "Cabrera",
      "Address": "3815 Randolph ST",
      "Phone_Number": "562 688 8744",
      "Email": "none",
      "Vehicle_One_License_Plate": "5TVV960",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Caliber",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 197
    },
    {
      "Id": 198,
      "First_Name": "Roberto",
      "Last_Name": "Aviles",
      "Address": "3815 Randolph ST",
      "Phone_Number": "323 915 3058",
      "Email": "none",
      "Vehicle_One_License_Plate": "6VQS020",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Altima",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 198
    },
    {
      "Id": 199,
      "First_Name": "Jose Ricardo",
      "Last_Name": "Cardenas",
      "Address": "3803 Randolph St #A",
      "Phone_Number": "323 773 6515",
      "Email": "cardenas2203@gmail.com",
      "Vehicle_One_License_Plate": "5EWX698",
      "Vehicle_One_Make": "Saturn",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2001,
      "Assigned_Parking_Stall_Number": 199
    },
    {
      "Id": 200,
      "First_Name": "Gabriela",
      "Last_Name": "Perez Villanueva",
      "Address": "3749 Randolph St",
      "Phone_Number": "310 780 1260",
      "Email": "gapevi12@yahoo.com",
      "Vehicle_One_License_Plate": "5WXC516",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Grand Caravan",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 200
    },
    {
      "Id": 201,
      "First_Name": "Hector",
      "Last_Name": "Trujillo",
      "Address": "3755 Randolph St",
      "Phone_Number": "323 770 4361",
      "Email": "hector.gettlove@gmail.com",
      "Vehicle_One_License_Plate": "8LQH683",
      "Vehicle_One_Make": "Chevrolet",
      "Vehicle_One_Model": "Tahoe",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 201
    },
    {
      "Id": 202,
      "First_Name": "Jimy",
      "Last_Name": "Ochoa",
      "Address": "3747 Randolph St",
      "Phone_Number": "213 446 7465",
      "Email": "none",
      "Vehicle_One_License_Plate": "18214F1",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Pickup",
      "Vehicle_One_Year": 1994,
      "Assigned_Parking_Stall_Number": 202
    },
    {
      "Id": 203,
      "First_Name": "Jimy",
      "Last_Name": "Ochoa",
      "Address": "3747 Randolph St",
      "Phone_Number": "213 446 7465",
      "Email": "none",
      "Vehicle_One_License_Plate": "27035Y2",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Pickup",
      "Vehicle_One_Year": 1994,
      "Assigned_Parking_Stall_Number": 203
    },
    {
      "Id": 204,
      "First_Name": "Carlos",
      "Last_Name": "Galdez",
      "Address": "3747 Randolph St",
      "Phone_Number": "323 736 9576",
      "Email": "none",
      "Vehicle_One_License_Plate": "5P85132",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Pick up",
      "Vehicle_One_Year": 1995,
      "Assigned_Parking_Stall_Number": 204
    },
    {
      "Id": 205,
      "First_Name": "Eduardo",
      "Last_Name": "Gonzalez",
      "Address": "3745 Randolph St",
      "Phone_Number": "323 470 4893",
      "Email": "geddy_f@hotmail.com",
      "Vehicle_One_License_Plate": "7ANB281",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2012,
      "Assigned_Parking_Stall_Number": 205
    },
    {
      "Id": 206,
      "First_Name": "Marcos",
      "Last_Name": "Cuevas",
      "Address": "3747 Randolph Pl Apt A",
      "Phone_Number": "323 401 5474",
      "Email": "marcocuevas74@yahoo.com",
      "Vehicle_One_License_Plate": "6UNT189",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Cobalt",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 206
    },
    {
      "Id": 207,
      "First_Name": "Brandon",
      "Last_Name": "Cortes",
      "Address": "6157 Orchard Ave Apt C",
      "Phone_Number": "323 970 8535",
      "Email": "brandoncortes73@gmail.com",
      "Vehicle_One_License_Plate": "8RDW384",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Mustang",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 207
    },
    {
      "Id": 208,
      "First_Name": "Ernesto",
      "Last_Name": "Madrid",
      "Address": "6163 Carmelita Ave Apt D",
      "Phone_Number": "323 480 7692",
      "Email": "madrid081891@gmail.com",
      "Vehicle_One_License_Plate": "7PRR041",
      "Vehicle_One_Make": "Pontiac",
      "Vehicle_One_Model": "G8 GT",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 208
    },
    {
      "Id": 209,
      "First_Name": "Maria Jesus",
      "Last_Name": "Flores",
      "Address": "6127 Orchard Ave",
      "Phone_Number": "323 493 4958",
      "Email": "mariadejflores@gmail.com",
      "Vehicle_One_License_Plate": "5NVZ047",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "Sorento",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 209
    },
    {
      "Id": 210,
      "First_Name": "Maribel",
      "Last_Name": "Alaniz",
      "Address": "3725 Randolph St Apt A",
      "Phone_Number": "323 873 0831",
      "Email": "maribel.alaniz1991@icloud",
      "Vehicle_One_License_Plate": "6XKR719",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 0,
      "Assigned_Parking_Stall_Number": 210
    },
    {
      "Id": 211,
      "First_Name": "Maribel",
      "Last_Name": "Alaniz",
      "Address": "3725 Randolph St Apt A",
      "Phone_Number": "323 873 0831",
      "Email": "maribel.alaniz1991@icloud.com",
      "Vehicle_One_License_Plate": "34566M2",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Colorado",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 211
    },
    {
      "Id": 212,
      "First_Name": "Mayra",
      "Last_Name": "Alvarez",
      "Address": "3725 Randolph St Apt C",
      "Phone_Number": "323 742 2606",
      "Email": "malvarez6965@gmail.com",
      "Vehicle_One_License_Plate": "7XAS833",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 212
    },
    {
      "Id": 221,
      "First_Name": "Antonio",
      "Last_Name": "Ibarra",
      "Address": "6164 Orchard Ave",
      "Phone_Number": "323 420 3920",
      "Email": "antonioibarra7575@gmail.com",
      "Vehicle_One_License_Plate": "6ZJH337",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Tahoe",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 221
    },
    {
      "Id": 222,
      "First_Name": "Cesar M.",
      "Last_Name": "Melendres",
      "Address": "3725 Randolph St Apt B",
      "Phone_Number": "323 942 0891",
      "Email": "none",
      "Vehicle_One_License_Plate": "01387B3",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Silverado",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 222
    },
    {
      "Id": 223,
      "First_Name": "Gerardo",
      "Last_Name": "Grande",
      "Address": "3723 Randolph PL",
      "Phone_Number": "626 923 7974",
      "Email": "ger.gran.20@gmail.com",
      "Vehicle_One_License_Plate": "7Y2L427",
      "Vehicle_One_Make": "Acura",
      "Vehicle_One_Model": "RL",
      "Vehicle_One_Year": 1996,
      "Assigned_Parking_Stall_Number": 223
    },
    {
      "Id": 224,
      "First_Name": "Brisas",
      "Last_Name": "Rivas",
      "Address": "3737 Randolph St",
      "Phone_Number": "213 281 0813",
      "Email": "brisa_rivas@yahoo.com",
      "Vehicle_One_License_Plate": "7XSK089",
      "Vehicle_One_Make": "Hyundai",
      "Vehicle_One_Model": "Tucson",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 224
    },
    {
      "Id": 225,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 225
    },
    {
      "Id": 226,
      "First_Name": "No Existing",
      "Last_Name": "Permit Holder",
      "Address": "",
      "Phone_Number": "",
      "Email": "",
      "Vehicle_One_License_Plate": "",
      "Vehicle_One_Make": "",
      "Vehicle_One_Model": "",
      "Vehicle_One_Year": "",
      "Assigned_Parking_Stall_Number": 226
    },
    {
      "Id": 227,
      "First_Name": "Yasmeen",
      "Last_Name": "Santos",
      "Address": "3647 Randolph St",
      "Phone_Number": "323 842 2560",
      "Email": "yasmeenn21@gmail.com",
      "Vehicle_One_License_Plate": "5JVT511",
      "Vehicle_One_Make": "Acura",
      "Vehicle_One_Model": "RSX",
      "Vehicle_One_Year": 2004,
      "Assigned_Parking_Stall_Number": 227
    },
    {
      "Id": 251,
      "First_Name": "Cesar",
      "Last_Name": "Melendres Jr",
      "Address": "3725 Randolph St Apt B",
      "Phone_Number": "323 942 0891",
      "Email": "None",
      "Vehicle_One_License_Plate": "6XZM052",
      "Vehicle_One_Make": "GMC",
      "Vehicle_One_Model": "Yukon XL",
      "Vehicle_One_Year": 2001,
      "Assigned_Parking_Stall_Number": 251
    },
    {
      "Id": 229,
      "First_Name": "Maria",
      "Last_Name": "Escobedo-Madrid",
      "Address": "6123 Loma Vista Ave",
      "Phone_Number": "323 687 7236",
      "Email": "mmadrid829@Gmail.com",
      "Vehicle_One_License_Plate": "8AZT778",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Traverse",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 229
    },
    {
      "Id": 230,
      "First_Name": "Maria",
      "Last_Name": "Escobedo-Madrid",
      "Address": "6123 Loma Vista Ave",
      "Phone_Number": "323 687 7236",
      "Email": "mmadrid829@gmail.com",
      "Vehicle_One_License_Plate": "8EWX497",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Equinox",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 230
    },
    {
      "Id": 231,
      "First_Name": "Jeffrey",
      "Last_Name": "Alaniz",
      "Address": "6170 Loma Vista Ave",
      "Phone_Number": "323 237 1523",
      "Email": "jeffreyalaniz.01@gmail.com",
      "Vehicle_One_License_Plate": "8KSZ534",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2013,
      "Assigned_Parking_Stall_Number": 231
    },
    {
      "Id": 232,
      "First_Name": "Ana",
      "Last_Name": "Flores",
      "Address": "3643 Randolph St",
      "Phone_Number": "323 570 7631",
      "Email": "ana.flores1354@gmail.com",
      "Vehicle_One_License_Plate": "8MNU817",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 232
    },
    {
      "Id": 233,
      "First_Name": "Hugo",
      "Last_Name": "Santos",
      "Address": "3647 Randolph St",
      "Phone_Number": "323 202 0564",
      "Email": "none",
      "Vehicle_One_License_Plate": "7EFE799",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Mustang",
      "Vehicle_One_Year": 2011,
      "Assigned_Parking_Stall_Number": 233
    },
    {
      "Id": 241,
      "First_Name": "Pedro",
      "Last_Name": "Mendez",
      "Address": "6114 Loma Vista Ave # A",
      "Phone_Number": "562 588 5054",
      "Email": "pmpmod2212@gmail.com",
      "Vehicle_One_License_Plate": "80691R2",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Tundra",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 241
    },
    {
      "Id": 242,
      "First_Name": "Armando Miguel",
      "Last_Name": "Lopez",
      "Address": "3646 E 61st Pl",
      "Phone_Number": "323 879 2152",
      "Email": "none",
      "Vehicle_One_License_Plate": "98979z2",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Tacoma",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 242
    },
    {
      "Id": 243,
      "First_Name": "Ana",
      "Last_Name": "Flores",
      "Address": "3643 Randolph St",
      "Phone_Number": "323 570 7631",
      "Email": "ana.flores1354@gmail.com",
      "Vehicle_One_License_Plate": "7TVX873",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Rav4",
      "Vehicle_One_Year": 2007,
      "Assigned_Parking_Stall_Number": 243
    },
    {
      "Id": 244,
      "First_Name": "Ana",
      "Last_Name": "Flores",
      "Address": "3643 Randolph St",
      "Phone_Number": "323 570 7631",
      "Email": "ana.flores1354@gmail.com",
      "Vehicle_One_License_Plate": "8DGM197",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Murano",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 244
    },
    {
      "Id": 245,
      "First_Name": "Bryan",
      "Last_Name": "Solano",
      "Address": "6171 Loma Vista Ave",
      "Phone_Number": "213 308 8485",
      "Email": "none",
      "Vehicle_One_License_Plate": "7MFA554",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 245
    },
    {
      "Id": 246,
      "First_Name": "Maria",
      "Last_Name": "Holguin",
      "Address": "3521 Randolph ST",
      "Phone_Number": "323 636 5462",
      "Email": "caramelo.holguin@gmail.com",
      "Vehicle_One_License_Plate": "8RHJ608",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Accord",
      "Vehicle_One_Year": 2020,
      "Assigned_Parking_Stall_Number": 246
    },
    {
      "Id": 247,
      "First_Name": "Francisco",
      "Last_Name": "Jimenez",
      "Address": "6161 Loma Vista Ave",
      "Phone_Number": "323 307 6867",
      "Email": "none",
      "Vehicle_One_License_Plate": "7YQU348",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Sentra",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 247
    },
    {
      "Id": 248,
      "First_Name": "Jennifer",
      "Last_Name": "Monroy",
      "Address": "3631 Randolph St",
      "Phone_Number": "323 945 7856",
      "Email": "monroyJ92@gmail.com",
      "Vehicle_One_License_Plate": "7WLF738",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 248
    },
    {
      "Id": 249,
      "First_Name": "Judith",
      "Last_Name": "Castaneda",
      "Address": "3631 Randolph St",
      "Phone_Number": "323 982 5525",
      "Email": "charmedjudy@gmail.com",
      "Vehicle_One_License_Plate": "8CSL050",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 249
    },
    {
      "Id": 250,
      "First_Name": "Candelario",
      "Last_Name": "Flores",
      "Address": "3631 Randolph St",
      "Phone_Number": 6196363625,
      "Email": "candelarioflo324@gmail.com",
      "Vehicle_One_License_Plate": "7ZMF047",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "CR-V",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 250
    },
    {
      "Id": 251,
      "First_Name": "Mireya",
      "Last_Name": "Olguin",
      "Address": "3603 Randolph St Apt A",
      "Phone_Number": "323 479 3913",
      "Email": "mayraolvera30@gmail.com",
      "Vehicle_One_License_Plate": "7VQH499",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Odyssey",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 251
    },
    {
      "Id": 252,
      "First_Name": "Agustin",
      "Last_Name": "Guerrero",
      "Address": "3625 Randolph St",
      "Phone_Number": "323 605 3239",
      "Email": "auguerr78@outlook.com",
      "Vehicle_One_License_Plate": "7WUK440",
      "Vehicle_One_Make": "Crystler",
      "Vehicle_One_Model": "Seabring",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 252
    },
    {
      "Id": 253,
      "First_Name": "Javier",
      "Last_Name": "Malagon",
      "Address": "3617 E 61st PL",
      "Phone_Number": "213 304 1616",
      "Email": "javiermalagon1964@gmail.com",
      "Vehicle_One_License_Plate": "4ZWG663",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Pathfinder",
      "Vehicle_One_Year": 1999,
      "Assigned_Parking_Stall_Number": 253
    },
    {
      "Id": 254,
      "First_Name": "Jacobo",
      "Last_Name": "Lujan",
      "Address": "3621 Randolph",
      "Phone_Number": "323 677 8762",
      "Email": "jacobo3621@gmail.com",
      "Vehicle_One_License_Plate": "6AYN117",
      "Vehicle_One_Make": "Nissan",
      "Vehicle_One_Model": "Exterra",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 254
    },
    {
      "Id": 255,
      "First_Name": "Luis",
      "Last_Name": "Garcia",
      "Address": "3611 Randolph St",
      "Phone_Number": "323 202 3829",
      "Email": "cindygarcia1283@gmail.com",
      "Vehicle_One_License_Plate": "7LQG017",
      "Vehicle_One_Make": "Acura",
      "Vehicle_One_Model": "MDX",
      "Vehicle_One_Year": 2003,
      "Assigned_Parking_Stall_Number": 255
    },
    {
      "Id": 256,
      "First_Name": "Jason",
      "Last_Name": "Garcia",
      "Address": "3611 Randolph st",
      "Phone_Number": "323 387 4236",
      "Email": "jasong3@uci.edu",
      "Vehicle_One_License_Plate": "6EAC472",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 256
    },
    {
      "Id": 257,
      "First_Name": "Michele",
      "Last_Name": "Zuniga",
      "Address": "3607 Randolph St",
      "Phone_Number": "323 799 8397",
      "Email": "none",
      "Vehicle_One_License_Plate": "7VB970",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 257
    },
    {
      "Id": 258,
      "First_Name": "Michele",
      "Last_Name": "Zuniga",
      "Address": "3607 Randolph St",
      "Phone_Number": "323 799 8397",
      "Email": "none",
      "Vehicle_One_License_Plate": "8AJT681",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Odyssey",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 258
    },
    {
      "Id": 259,
      "First_Name": "Gerardo",
      "Last_Name": "Cruz",
      "Address": "3607 Randolph St",
      "Phone_Number": "626 494 3691",
      "Email": "gcruzcorona67@gmail.com",
      "Vehicle_One_License_Plate": "352749M2",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "F150",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 259
    },
    {
      "Id": 260,
      "First_Name": "Alfredo",
      "Last_Name": "Cruz",
      "Address": "3603 Randolph St",
      "Phone_Number": "323 440 3396",
      "Email": "none",
      "Vehicle_One_License_Plate": "26743J1",
      "Vehicle_One_Make": "Dodge",
      "Vehicle_One_Model": "Ram",
      "Vehicle_One_Year": 2008,
      "Assigned_Parking_Stall_Number": 260
    },
    {
      "Id": 261,
      "First_Name": "Juan Jose",
      "Last_Name": "Cervantes",
      "Address": "3537 Randolph St",
      "Phone_Number": "323 214 9195",
      "Email": "pepe_76@yahoo.com",
      "Vehicle_One_License_Plate": "8FDT477",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2018,
      "Assigned_Parking_Stall_Number": 261
    },
    {
      "Id": 262,
      "First_Name": "Alfredo",
      "Last_Name": "Cruz",
      "Address": "3603 Randolph St",
      "Phone_Number": "323 440 3396",
      "Email": "none",
      "Vehicle_One_License_Plate": "85651S2",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "F150",
      "Vehicle_One_Year": 2011,
      "Assigned_Parking_Stall_Number": 262
    },
    {
      "Id": 263,
      "First_Name": "Martina",
      "Last_Name": "Cruz",
      "Address": "3603 Randolph St",
      "Phone_Number": "323 637 0866",
      "Email": "none",
      "Vehicle_One_License_Plate": "7TNU618",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Odyssey",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 263
    },
    {
      "Id": 264,
      "First_Name": "Fidel",
      "Last_Name": "Ulloa",
      "Address": "3533 Randolph St",
      "Phone_Number": "323 412 2266",
      "Email": "fidelulloa78@gmail.com",
      "Vehicle_One_License_Plate": "6WKE930",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Sienna",
      "Vehicle_One_Year": 1998,
      "Assigned_Parking_Stall_Number": 264
    },
    {
      "Id": 265,
      "First_Name": "Karla",
      "Last_Name": "Miranda",
      "Address": "3533 Randolph St",
      "Phone_Number": "323 300 0444",
      "Email": "johanarodas2006@gmail.com",
      "Vehicle_One_License_Plate": "6TIZ574",
      "Vehicle_One_Make": "GMC",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2001,
      "Assigned_Parking_Stall_Number": 265
    },
    {
      "Id": 266,
      "First_Name": "Angela",
      "Last_Name": "Moran",
      "Address": "3530 E 61pl Apt E",
      "Phone_Number": "323 779 0796",
      "Email": "none",
      "Vehicle_One_License_Plate": "8ETP723",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 266
    },
    {
      "Id": 267,
      "First_Name": "Gabriela",
      "Last_Name": "Moreno",
      "Address": "3530 E 61PL Apt G",
      "Phone_Number": "213 713 2954",
      "Email": "none",
      "Vehicle_One_License_Plate": "8LSP469",
      "Vehicle_One_Make": "Jeep",
      "Vehicle_One_Model": "none",
      "Vehicle_One_Year": 2019,
      "Assigned_Parking_Stall_Number": 267
    },
    {
      "Id": 268,
      "First_Name": "Patricia",
      "Last_Name": "Ortiz",
      "Address": "3529 Randolph St",
      "Phone_Number": "323 819 8945",
      "Email": "portiz741@gmail.com",
      "Vehicle_One_License_Plate": "8UWW144",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Civic",
      "Vehicle_One_Year": 2021,
      "Assigned_Parking_Stall_Number": 268
    },
    {
      "Id": 269,
      "First_Name": "Elmer",
      "Last_Name": "Arce",
      "Address": "3525 Randolph St",
      "Phone_Number": "323 470 2426",
      "Email": "elmerpera87@hotmail.com",
      "Vehicle_One_License_Plate": "5MBJ616",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 269
    },
    {
      "Id": 270,
      "First_Name": "Elmer",
      "Last_Name": "Arce",
      "Address": "3525 Randolph St",
      "Phone_Number": "323 470 2426",
      "Email": "elmerpera87@hotmail.com",
      "Vehicle_One_License_Plate": "ARCE27",
      "Vehicle_One_Make": "Ford",
      "Vehicle_One_Model": "Mustang",
      "Vehicle_One_Year": 2016,
      "Assigned_Parking_Stall_Number": 270
    },
    {
      "Id": 271,
      "First_Name": "Jose",
      "Last_Name": "Riestra",
      "Address": "6156 Maywood Avr",
      "Phone_Number": "323 518 6352",
      "Email": "jose.riestra@yahoo.com",
      "Vehicle_One_License_Plate": "7TOJ434",
      "Vehicle_One_Make": "Chevy",
      "Vehicle_One_Model": "Tahoe",
      "Vehicle_One_Year": 2002,
      "Assigned_Parking_Stall_Number": 271
    },
    {
      "Id": 272,
      "First_Name": "Armando",
      "Last_Name": "Santana",
      "Address": "3519 Randolph St",
      "Phone_Number": "213 453 5578",
      "Email": "none",
      "Vehicle_One_License_Plate": "7KHK847",
      "Vehicle_One_Make": "Kia",
      "Vehicle_One_Model": "4D",
      "Vehicle_One_Year": 2015,
      "Assigned_Parking_Stall_Number": 272
    },
    {
      "Id": 273,
      "First_Name": "Oscar",
      "Last_Name": "Holguin",
      "Address": "3519 Randolph ST",
      "Phone_Number": "323 826 4816",
      "Email": "oscarh323@gmail.com",
      "Vehicle_One_License_Plate": "7VJGG047",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Corolla",
      "Vehicle_One_Year": 2017,
      "Assigned_Parking_Stall_Number": 273
    },
    {
      "Id": 274,
      "First_Name": "Livida",
      "Last_Name": "Portillo de Pleitez",
      "Address": "3516 E 61st Pl",
      "Phone_Number": "323 271 5163",
      "Email": "none",
      "Vehicle_One_License_Plate": "6HAH545",
      "Vehicle_One_Make": "Toyota",
      "Vehicle_One_Model": "Camry",
      "Vehicle_One_Year": 2005,
      "Assigned_Parking_Stall_Number": 274
    },
    {
      "Id": 275,
      "First_Name": "Amber Lynn",
      "Last_Name": "Wheeler",
      "Address": "3519 Randolph St",
      "Phone_Number": "323 812 5984",
      "Email": "trainwithamberlynn@gmail.com",
      "Vehicle_One_License_Plate": "6JPM050",
      "Vehicle_One_Make": "Honda",
      "Vehicle_One_Model": "Odessey",
      "Vehicle_One_Year": 2009,
      "Assigned_Parking_Stall_Number": 275
    }
  ];